### ISSUE TITLE
Nothing generated from vHive profiling tool

### ISSUE THREAD

**Issue by dhuang-esl** [vhive-serverless/vHive#498]
**Describe the bug**
I run the vHive profiling tool following [this tutorial](https://github.com/ease-lab/vhive/blob/pmu_tutorial_session/docs/profiling.md#pre-requisites). However the profile.csv is not generated. I think the profiling step has been skipped somehow. Please refer to the following log section.

**To Reproduce**
On a Cloudlab node:
```
git clone https://github.com/ease-lab/vhive.git
cd vhive
then following the profiling tutorial to launch the experiment
```

**Logs**
```
~/vhive$ sudo env "PATH=$PATH" go test -v -timeout 99999s -run TestProfileSingleConfiguration -args -funcNames helloworld -vm 1 -rps 20 -l 1
INFO[2022-03-09T07:03:02.582939321-07:00] Orchestrator snapshots enabled: false
INFO[2022-03-09T07:03:02.583035286-07:00] Orchestrator UPF enabled: false
INFO[2022-03-09T07:03:02.583058286-07:00] Orchestrator lazy serving mode enabled: false
INFO[2022-03-09T07:03:02.583068413-07:00] Orchestrator UPF metrics enabled: false
INFO[2022-03-09T07:03:02.583080771-07:00] Drop cache: true
INFO[2022-03-09T07:03:02.583095482-07:00] Bench dir: bench_results
INFO[2022-03-09T07:03:02.583108479-07:00] Registering bridges for tap manager
INFO[2022-03-09T07:03:02.584695283-07:00] Creating containerd client
INFO[2022-03-09T07:03:02.585429969-07:00] Created containerd client
INFO[2022-03-09T07:03:02.585449706-07:00] Creating firecracker client
INFO[2022-03-09T07:03:02.585535175-07:00] Created firecracker client
=== RUN   TestProfileSingleConfiguration
    perf_bench_test.go:137: Skipping TestProfileSingleConfiguration
--- SKIP: TestProfileSingleConfiguration (0.00s)
PASS
INFO[2022-03-09T07:03:02.585725163-07:00] waiting for goroutines
INFO[2022-03-09T07:03:02.585740391-07:00] waiting done
INFO[2022-03-09T07:03:02.585749372-07:00] Closing fcClient
INFO[2022-03-09T07:03:02.585760299-07:00] Closing containerd client
INFO[2022-03-09T07:03:02.585778188-07:00] Removing bridges
ok      github.com/ease-lab/vhive       0.234s
```

**Solution**
Line 137 of `perf_bench_test.go` should be commented out, according to: https://github.com/ease-lab/vSwarm/issues/60

**Comment by niravnshah** [comment]
Along with line 137, we also need to comment out line 89 in perf_bench_test.go

**Comment by niravnshah** [comment]
Some additional information. May be helpful for this issue.
I tried to run `make test` and after showing many tests to be passing, i get following output towards the end.
```
sudo mkdir -m777 -p /tmp/ctrd-logs && sudo env "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/nshah5/vhive/istio-1.12.5/bin:/usr/local/go/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin" /usr/local/bin/firecracker-containerd --config /etc/firecracker-containerd/config.toml 1>/tmp/ctrd-logs/fccd_orch_noupf_log_bench.out 2>/tmp/ctrd-logs/fccd_orch_noupf_log_bench.err &
sudo env "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/nshah5/vhive/istio-1.12.5/bin:/usr/local/go/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin:/home/nshah5/vhive/istio-1.12.5/bin" go test -short -v -race -cover -run TestProfileSingleConfiguration -args -test -loadStep 100 && sudo rm -rf bench_results
INFO[2022-09-14T06:32:43.139213242-07:00] Orchestrator snapshots enabled: false
INFO[2022-09-14T06:32:43.139334933-07:00] Orchestrator UPF enabled: false
INFO[2022-09-14T06:32:43.139352415-07:00] Orchestrator inMemWorkingSet enabled: false
INFO[2022-09-14T06:32:43.139369311-07:00] Orchestrator lazy serving mode enabled: false
INFO[2022-09-14T06:32:43.139385840-07:00] Orchestrator UPF metrics enabled: false
INFO[2022-09-14T06:32:43.139401530-07:00] Drop cache: true
INFO[2022-09-14T06:32:43.139416414-07:00] Bench dir: bench_results
INFO[2022-09-14T06:32:43.139435411-07:00] Registering bridges for tap manager
INFO[2022-09-14T06:32:43.140026361-07:00] Creating containerd client
INFO[2022-09-14T06:32:43.140990512-07:00] Created containerd client
INFO[2022-09-14T06:32:43.141110011-07:00] Creating firecracker client
INFO[2022-09-14T06:32:43.141563396-07:00] Created firecracker client
=== RUN   TestProfileSingleConfiguration
INFO[2022-09-14T06:32:43.174590566-07:00] New function added                            fID=0 image="ghcr.io/ease-lab/helloworld:var_workload" isPinned=true servedTh=0
WARN[2022-09-14T06:32:53.820615244-07:00] Failed to Fetch k8s dns clusterIP exit status 1
The connection to the server localhost:8080 was refused - did you specify the right host or port?

WARN[2022-09-14T06:32:53.820834234-07:00] Using google dns 8.8.8.8
INFO[2022-09-14T06:32:55.281169698-07:00] New function added                            fID=1 image="ghcr.io/ease-lab/helloworld:var_workload" isPinned=true servedTh=0
WARN[2022-09-14T06:32:55.303196825-07:00] Failed to Fetch k8s dns clusterIP exit status 1
The connection to the server localhost:8080 was refused - did you specify the right host or port?

WARN[2022-09-14T06:32:55.303279655-07:00] Using google dns 8.8.8.8
INFO[2022-09-14T06:32:56.800111163-07:00] Current RPS: 10
WARN[2022-09-14T06:32:56.800411068-07:00] Too many latency samples for 2 VM, measure 20 samples instead.
    perf_bench_test.go:389:
                Error Trace:    /home/nshah5/vhive/perf_bench_test.go:389
                                                        /home/nshah5/vhive/perf_bench_test.go:156
                Error:          Received unexpected error:
                                open profile.csv: no such file or directory
                Test:           TestProfileSingleConfiguration
                Messages:       Stopping profiler returned error: open profile.csv: no such file or directory
--- FAIL: TestProfileSingleConfiguration (34.67s)
FAIL
coverage: 34.1% of statements
INFO[2022-09-14T06:33:17.810474826-07:00] waiting for goroutines
INFO[2022-09-14T06:33:29.086403073-07:00] waiting done
INFO[2022-09-14T06:33:29.086621409-07:00] Closing fcClient
INFO[2022-09-14T06:33:29.086771383-07:00] Closing containerd client
INFO[2022-09-14T06:33:29.087000174-07:00] Removing bridges
exit status 1
```
This is also failing with similar error message that profile.csv is not found.
apart from this, it is also showing this error.
```
WARN[2022-09-14T06:32:55.303196825-07:00] Failed to Fetch k8s dns clusterIP exit status 1
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Do we need to be running a k8s cluster to be able to run profiling tool?

I tried to have a single node cluster running while trying to execute the profiling tool, however, in that case the profiling tool exited with this error
```
nshah5@d8eb97bf800a:~/vhive$ sudo env "PATH=$PATH" go test -v -timeout 99999s -run TestProfileIncrementConfiguration -args -funcNames helloworld -vmIncrStep 4 -maxVMNum 32 -nodes '!+Memory_Bound*/3,+MUX'
INFO[2022-09-14T05:02:17.733118141-07:00] Orchestrator snapshots enabled: false
INFO[2022-09-14T05:02:17.733147065-07:00] Orchestrator UPF enabled: false
INFO[2022-09-14T05:02:17.733150249-07:00] Orchestrator lazy serving mode enabled: false
INFO[2022-09-14T05:02:17.733154457-07:00] Orchestrator UPF metrics enabled: false
INFO[2022-09-14T05:02:17.733157474-07:00] Drop cache: true
INFO[2022-09-14T05:02:17.733159560-07:00] Bench dir: bench_results
INFO[2022-09-14T05:02:17.733162427-07:00] Registering bridges for tap manager
PANI[2022-09-14T05:02:17.733191966-07:00] Bridge could not be created                   bridge=br0
panic: (*logrus.Entry) 0xc0003b5500

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003b5490, 0x0, {0xc0002fee00, 0x1b})
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x47e
github.com/sirupsen/logrus.(*Entry).Log(0xc0003b5490, 0x0, {0xc0002df998?, 0x604?, 0x0?})
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/ease-lab/vhive/taps.createBridge({0xc00042c1c4, 0x3}, {0xc00042c1d0, 0xb})
        /home/nshah5/vhive/taps/tapManager.go:90 +0x297
github.com/ease-lab/vhive/taps.NewTapManager()
        /home/nshah5/vhive/taps/tapManager.go:72 +0x17d
github.com/ease-lab/vhive/misc.NewVMPool(...)
        /home/nshah5/vhive/misc/vm_pool.go:34
github.com/ease-lab/vhive/ctriface.NewOrchestrator({0x153c787, 0x9}, {0x0, 0x0}, {0xc0002dfe90, 0x5, 0x1?})
        /home/nshah5/vhive/ctriface/orch.go:99 +0x85
github.com/ease-lab/vhive.TestMain(0x84b311?)
        /home/nshah5/vhive/vhive_test.go:75 +0x465
main.main()
        _testmain.go:83 +0x1d3
exit status 2
FAIL    github.com/ease-lab/vhive       0.006s
```

**Comment by niravnshah** [comment]
Hi @ustiugov, I am trying to get the vHive profiling tool working to get the function cold start delay numbers. Any help in getting this profiling tool working would be highly appreciated. Is it possible to look into this issue? Or if you can provide some pointers also would be helpful.

Thanks,
Nirav.

**Comment by ustiugov** [comment]
@niravnshah sorry for the late response. k8s setup is not required for the profiler to run. 

`Bridge could not be created                   bridge=br0` error indicates that you ran vHive repeatedly without cleaning the host setup after the previous run failed (and didn't delete the bridge because it died). You need to run the cleaning script as specified [here](https://github.com/vhive-serverless/vHive/blob/main/docs/quickstart_guide.md#2-clean-up).

Re: the missing file, please try to drill down the error. Currently, the profiler is not fully supported due to problems in its CI testing but we would love to bring it back. We would welcome contributions from the community.

**Comment by ustiugov** [comment]
@niravnshah please advise if you were able to solve the problem

**Comment by niravnshah** [comment]
Hi @ustiugov, not yet. I am still hitting the "Bridge could not be created" error. I feel it might be due to my system being behind a proxy, i tried to put multiple ip address in no_proxy but couldn't get it working.

**Comment by ustiugov** [comment]
no, I believe that this has nothing to do with the proxy. can you list all the bridges and see if there is already a bridge with the name br0?

**Comment by niravnshah** [comment]
ok got the issue. It was unsupported CPU for toplev as i am running on a test system
![image](https://user-images.githubusercontent.com/73517208/209934642-5d44aeec-51c3-42c0-bd34-cfc10a4bc93e.png)

Due to this profile.csv was not generated. 
Added "--force-cpu" option to get it working.

**Comment by ustiugov** [comment]
i see, thanks for sharing. Please close the issue if it's resolved

**Comment by ustiugov** [comment]
@niravnshah

**Comment by niravnshah** [comment]
@ustiugov, I am not getting the option to close the issue. Perhaps as i am not the one who opened it.
![image](https://user-images.githubusercontent.com/73517208/210033573-41e1bec7-1c4a-4e17-8212-bb3bd6921505.png)
@dhuang-esl, can you please check if the solution mentioned by me [above](https://github.com/vhive-serverless/vHive/issues/498#issuecomment-1367205155) works for you as well? and if so, can you please close the issue?

**Comment by ustiugov** [comment]
ah , sorry. closing. @dhuang-esl please re-open if still relevant.
