### ISSUE TITLE
Unable to connect Workers with Master node 

### ISSUE THREAD

**Issue by anshalshukla** [vhive-serverless/vHive#677]
**Describe the bug**
The worker node is unable to connect to the master node.

**To Reproduce**
Follow the steps in quickstart guide.

**Logs**
```
anshal@node-1:~/vhive$ sudo kubeadm join 198.22.255.11:6443 --token whir9i.n6txv9nawcf864kh \
> --discovery-token-ca-cert-hash sha256:2f983d50ff42e195deaecc952c8e3c76008c4e3e31347e1f5db4a233834f6898 > >(tee -a /tmp/vhive-logs/kubeadm_join.stdout) 2> >(tee -a /tmp/vhive-logs/kubeadm_join.stderr >&2)
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W0221 03:37:37.312188   32963 utils.go:69] The recommended value for "resolvConf" in "KubeletConfiguration" is: /run/systemd/resolve/resolv.conf; the provided value is: /run/systemd/resolve/resolv.conf
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
error execution phase kubelet-start: error uploading crisocket: nodes "node-1.vhive-rs440.ntu-cloud-pg0.cloudlab.umass.edu" not found
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by ustiugov** [comment]
@leokondrashov can you reproduce this behavior?

**Comment by leokondrashov** [comment]
Yes, I reproduced this for newest main branch.

Looking into journalctl on worker node, I see that kubelet is constantly failing to restart beacuse there is no such thing as `/etc/vhive-cri/vhive-cri.sock` which should be created by vHive. But vHive is failing as well:
```
$ sudo bash -c "./vhive > >(tee -a /tmp/vhive-logs/vhive.stdout) 2> >(tee -a /tmp/vhive-logs/vhive.stderr >&2)"
time="2023-02-21T05:16:26.438443983-06:00" level=info msg="Registering bridges for tap manager"
time="2023-02-21T05:16:26.438603409-06:00" level=panic msg="Bridge could not be created" bridge=br0
panic: (*logrus.Entry) 0xc0003f99d0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003f9960, 0x0, {0xc000312ac0, 0x1b})
	/users/lkondras/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x47e
github.com/sirupsen/logrus.(*Entry).Log(0xc0003f9960, 0x0, {0xc00035fa28?, 0x604?, 0x0?})
	/users/lkondras/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/users/lkondras/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/vhive-serverless/vhive/taps.createBridge({0xc0002a3878, 0x3}, {0xc0002a3880, 0xb})
	/users/lkondras/vhive/taps/tapManager.go:90 +0x297
github.com/vhive-serverless/vhive/taps.NewTapManager()
	/users/lkondras/vhive/taps/tapManager.go:72 +0x17d
github.com/vhive-serverless/vhive/misc.NewVMPool(...)
	/users/lkondras/vhive/misc/vm_pool.go:34
github.com/vhive-serverless/vhive/ctriface.NewOrchestrator({0x122a852, 0x9}, {0x0, 0x0}, {0xc00035ff40, 0x5, 0x37?})
	/users/lkondras/vhive/ctriface/orch.go:98 +0x85
main.main()
	/users/lkondras/vhive/vhive.go:137 +0x899
```
